### ISSUE TITLE
Suggestion for module

### ISSUE THREAD

**Issue by demotech89** [dogstarrb/pf2e-legacy-content#5]
Hey, I think this module is awesome while transitioning with PF2, but if I can make a suggestion. With the Legacy Module installed, every drop down has two of each option as shown in the pictures below. It might be a good idea to have (Legacy) after each name so players can know which one to select when creating a character. Such as Warpriest (Legacy) could be an example that shows up in drop downs. 

Thanks for hearing my suggestion. 

<img width="212" alt="Legacy" src="https://github.com/dogstarrb/pf2e-legacy-content/assets/147771452/bd5ca733-aede-4417-ba43-8f1892f06943">
<img width="163" alt="Legacy2" src="https://github.com/dogstarrb/pf2e-legacy-content/assets/147771452/59d461b8-47c5-4eff-98ac-0488385393ea">

**Comment by TikaelSol** [comment]
The first of each of those will be the system's version. A future update may append `(legacy)` to items in the module.
