### ISSUE TITLE
Weapons, Armors and Shields do not show up in the Compendium Browser

### ISSUE THREAD

**Issue by felix-schneider** [dogstarrb/pf2e-legacy-content#7]
My compendium browser settings are attached:
![image](https://github.com/dogstarrb/pf2e-legacy-content/assets/208336/fce9f2f6-4ab6-405c-a2b2-758f944b8638)
![image](https://github.com/dogstarrb/pf2e-legacy-content/assets/208336/f1c7a8fe-5aa7-46a2-bf10-388be909021c)

Other items (consumables, treasures etc.) show up, but weapons, armors and shields are not there.
![image](https://github.com/dogstarrb/pf2e-legacy-content/assets/208336/c6350f10-9ca7-4cc9-943b-51f6bc89ae4c)
![image](https://github.com/dogstarrb/pf2e-legacy-content/assets/208336/69ee5162-da4a-4c2f-b1c7-068bd9304cf9)

**Comment by TikaelSol** [comment]
Likely to do with the system having changed the structure of those item types, it's fixed by migrating the legacy equipment compendium (right click the unlocked compendium and choose migration status).

**Comment by felix-schneider** [comment]
Cool, that worked, thanks!
